### ISSUE TITLE
Not supported for 1.9.4

### ISSUE THREAD

**Issue by FreddieFoxtrot** [DavideBlade/Clash-of-Minecrafters#1]
Could I get a 1.9.4 Update please :) 
Error on 1.9.4 load: 
`[17:25:39 ERROR]: Could not load 'plugins/CoM.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: a/a/a/a/a : Unsupported major.minor version 52.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot.jar:git-Spigot-4af49dc-23da8b0]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot.jar:git-Spigot-4af49dc-23da8b0]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot.jar:git-Spigot-4af49dc-23da8b0]
        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugins(CraftServer.java:296) [spigot.jar:git-Spigot-4af49dc-23da8b0]
        at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:200) [spigot.jar:git-Spigot-4af49dc-23da8b0]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532) [spigot.jar:git-Spigot-4af49dc-23da8b0]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_99]
Caused by: java.lang.UnsupportedClassVersionError: a/a/a/a/a : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_99]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:803) ~[?:1.7.0_99]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_99]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0_99]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0_99]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0_99]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_99]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_99]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_99]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-4af49dc-23da8b0]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-4af49dc-23da8b0]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_99]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_99]
        at java.lang.Class.forName0(Native Method) ~[?:1.7.0_99]
        at java.lang.Class.forName(Class.java:278) ~[?:1.7.0_99]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-4af49dc-23da8b0]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot.jar:git-Spigot-4af49dc-23da8b0]
        ... 6 more
`

**Comment by DavideBlade** [comment]
Clash of Minecrafters work with 1.8.x only as you can see on the plugin page.

**Comment by FreddieFoxtrot** [comment]
I'm aware that it says "Tested for 1.8" so figured I'd give it a try and hope for the best, didn't expect it to but thought I'd throw down an update request to see if and when an update would be ready.

And this was not an issue, but your spigot page lists this as the area to ask questions AND report issues, so consider this a question.

**Comment by DavideBlade** [comment]
I'll update to 1.9 as soon worldedit allows.

**Comment by FreddieFoxtrot** [comment]
Go to the world-edit jenkins, they have a stable release up to 1.9.4 on there.

**Comment by DavideBlade** [comment]
I know that but these are builds, not really stable version.

**Comment by DavideBlade** [comment]
In the next update you can find support for 1.9 :).
